# -*- coding: utf-8 -*-
"""
Initial schema migration for SMP12C VibroDiag Analyzer v1.3

Creates tables:
- turbines
- archives
- sensor_data
- analysis_cache
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Турбины
    op.create_table(
        'turbines',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('wtg_id', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('wtg_id')
    )
    op.create_index('idx_turbines_wtg_id', 'turbines', ['wtg_id'], unique=False)
    
    # Архивы
    op.create_table(
        'archives',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('turbine_id', sa.Integer(), nullable=False),
        sa.Column('file_path', sa.String(length=500), nullable=True),
        sa.Column('file_hash', sa.String(length=64), nullable=False),
        sa.Column('record_datetime', sa.DateTime(), nullable=True),
        sa.Column('file_size_kb', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['turbine_id'], ['turbines.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('file_hash')
    )
    op.create_index('idx_archives_file_hash', 'archives', ['file_hash'], unique=True)
    op.create_index('idx_archive_turbine_datetime', 'archives', ['turbine_id', 'record_datetime'], unique=False)
    
    # Данные датчиков
    op.create_table(
        'sensor_data',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('archive_id', sa.Integer(), nullable=False),
        sa.Column('sensor_id', sa.Integer(), nullable=False),
        sa.Column('filter_type', sa.String(length=20), nullable=False),
        sa.Column('timestamps', postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column('values', postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column('sampling_frequency', sa.Float(), nullable=True),
        sa.Column('samples_count', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['archive_id'], ['archives.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('archive_id', 'sensor_id', 'filter_type', name='uix_sensor_data')
    )
    op.create_index('idx_sensor_data_archive', 'sensor_data', ['archive_id'], unique=False)
    op.create_index('idx_sensor_data_sensor', 'sensor_data', ['sensor_id', 'filter_type'], unique=False)
    
    # Кэш анализа
    op.create_table(
        'analysis_cache',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('archive_id', sa.Integer(), nullable=False),
        sa.Column('sensor_id', sa.Integer(), nullable=False),
        sa.Column('filter_type', sa.String(length=20), nullable=False),
        sa.Column('rms_total', sa.Float(), nullable=True),
        sa.Column('zone', sa.String(length=1), nullable=True),
        sa.Column('peak', sa.Float(), nullable=True),
        sa.Column('peak_to_peak', sa.Float(), nullable=True),
        sa.Column('spectrum_frequencies', postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column('spectrum_amplitudes', postgresql.ARRAY(sa.Float()), nullable=True),
        sa.Column('peaks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('analyzed_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['archive_id'], ['archives.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('archive_id', 'sensor_id', 'filter_type', name='uix_analysis_cache')
    )
    op.create_index('idx_analysis_cache_archive', 'analysis_cache', ['archive_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_analysis_cache_archive', table_name='analysis_cache')
    op.drop_table('analysis_cache')
    op.drop_index('idx_sensor_data_sensor', table_name='sensor_data')
    op.drop_index('idx_sensor_data_archive', table_name='sensor_data')
    op.drop_table('sensor_data')
    op.drop_index('idx_archive_turbine_datetime', table_name='archives')
    op.drop_index('idx_archives_file_hash', table_name='archives')
    op.drop_table('archives')
    op.drop_index('idx_turbines_wtg_id', table_name='turbines')
    op.drop_table('turbines')
    # ### end Alembic commands ###
